module.exports = {
  INCONSISTENT_INPUT: "INCONSISTENT_INPUT",
  TIMEOUT_ERROR: "TIMEOUT_ERROR",
  CONNECT_TIMEOUT_ERROR: "CONNECT_TIMEOUT_ERROR",
  SEARCH_ERROR: "SEARCH_ERROR",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  UNEXPECTED_ERROR: "UNEXPECTED_ERROR",
};
